CREATE DATABASE IF NOT EXISTS book_reviews;

USE book_reviews;

CREATE TABLE IF NOT EXISTS reviews (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    review TEXT NOT NULL,
    score INT NOT NULL,
    createdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedate TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

FLUSH PRIVILEGES;
